"""
pythoneda/realm/unveilingpartner/application/unveilingpartner_app.py

This file can be used to run UnveilingPartner's PythonEDA realm.

Copyright (C) 2023-today rydnr's pythoneda-realm-unveilingpartner/application

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
import asyncio
from pythoneda.application import PythonEDA


class UnveilingpartnerApp(PythonEDA):
    """
    Runs the UnveilingPartner's PythonEDA realm.

    Class name: UnveilingpartnerApp

    Responsibilities:
        - Runs the UnveilingPartner's PythonEDA realm.

    Collaborators:
        - Command-line handlers from pythoneda-realm-unveilingpartner/infrastructure
    """

    def __init__(self):
        """
        Creates a new Rydnr instance.
        """
        # unveilingpartner_banner is automatically generated by pythoneda-realm-unveilingpartner/application-artifact
        try:
            from pythoneda.realm.unveilingpartner.application.unveilingpartner_banner import (
                UnveilingpartnerBanner,
            )
            banner = UnveilingpartnerBanner()
        except ImportError:
            banner = None

        super().__init__(banner, __file__)


if __name__ == "__main__":
    asyncio.run(
        UnveilingpartnerApp.main("pythoneda.realm.unveilingpartner.Unveilingpartner")
    )
