# vim: set fileencoding=utf-8
"""
pythoneda/realm/unveilingpartner/application/unveilingpartner_app.py

This file can be used to run UnveilingPartner's PythonEDA realm.

Copyright (C) 2023-today rydnr's pythoneda-realm-unveilingpartner/application

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
import asyncio
from dbus_next import BusType
from pythoneda.shared.application import enable, PythonEDA
from pythoneda.shared.artifact.events.code.infrastructure.dbus import (
    DbusChangeStagingCodeExecutionPackaged,
)


@enable(
    UnveilingPartnerDbusDbusSignalListener,
    events=[
        {
            "event-class": DbusChangeStagingCodeExecutionPackaged,
            "bus-type": BusType.SYSTEM,
        },
    ],
)
class UnveilingpartnerApp(PythonEDA):
    """
    Runs the UnveilingPartner's PythonEDA realm.

    Class name: UnveilingpartnerApp

    Responsibilities:
        - Runs the UnveilingPartner's PythonEDA realm.

    Collaborators:
        - Command-line handlers from pythoneda-realm-unveilingpartner/infrastructure
    """

    def __init__(self, name: str):
        """
        Creates a new UnveilingpartnerApp instance.
        :param name: The app name.
        :type name: str
        """
        # unveilingpartner_banner is automatically generated by pythoneda-realm-unveilingpartner/application-artifact
        try:
            from pythoneda.realm.unveilingpartner.application.unveilingpartner_banner import (
                UnveilingpartnerBanner,
            )

            banner = UnveilingpartnerBanner()
        except ImportError:
            banner = None

        super().__init__(name, banner, __file__)


if __name__ == "__main__":
    asyncio.run(UnveilingpartnerApp.main())
# vim: syntax=python ts=4 sw=4 sts=4 tw=79 sr et
# Local Variables:
# mode: python
# python-indent-offset: 4
# tab-width: 4
# indent-tabs-mode: nil
# fill-column: 79
# End:
